name: Release

on:
  push:
    branches:
      - main
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@master
        with:
          # This makes Actions fetch all Git history so that Changesets
          # can generate changelogs with the correct commits.
          fetch-depth: 0

      - name: Set up Node.js 16.4.0
        uses: actions/setup-node@master
        with:
          node-version: 16.4.0

      - name: Install dependencies
        run: yarn install

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@master
        with:
          version: yarn changeset version
          publish: yarn release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
